JoinColony/purser

.github/CONTRIBUTE.md
README.md
docs/_Docs_Contribute.md
modules/node_modules/@colony/purser-core/README.md
modules/node_modules/@colony/purser-ledger/README.md
modules/node_modules/@colony/purser-metamask/README.md
modules/node_modules/@colony/purser-software/README.md
modules/node_modules/@colony/purser-trezor/README.md

This PR updates the link from the various documentation documents inside the repo to the `CONTRIBUTE.md` file.
These links were either broken or used an outdated reference.

Update link to CONTRIBUTE.md

---

package.json
yarn.lock

This PR updates the following dependencies, that were not automatically updated by GK:
- `eslint-plugin-flowtype` #133 
- `lint-staged` #135 
- `prettier` #134 
- `ethers` #136 
This is due to a `git commit` error happening in the CI build initiated by the `greenkeeper-lockfile-update` binary.
The fix for this will come in a separate PR
Resolves #133 
Resolves #134 
Resolves #135 
Resolves #136

Manually update packages not handled by Greenkeeper

---

.circleci/config.yml
package.json
yarn.lock

This PR removes the `greenkeeper-lockfile` package and it's related CI build job.
This is because Greenkeeper _(now)_ supports this natively for public packages: https://blog.greenkeeper.io/announcing-native-lockfile-support-85381a37a0d0
This should now fix all the latest greenkeeper failed updates.

Remove manual Greenkeeper lockfile update

---

modules/node_modules/@colony/purser-core/index.js
modules/node_modules/@colony/purser-ledger/index.js
modules/node_modules/@colony/purser-metamask/index.js
modules/node_modules/@colony/purser-software/index.js
modules/node_modules/@colony/purser-trezor/index.js

This PR fixes an oversight with the initial release of the library, which only had `default` exports for the index files.
This PR changes all modules `index.js` file to also add a named export to each exposed method, alongside the `default` one.
Modules:
_**Note:** This does not require a documentation update, as all the docs already assume named exports exist_

Add correct modules named exports

---

docs/_Interface_Common_Wallet_Interface.md

This PR fixes a small spelling mistake inside the [Common Wallet Interface docs](https://docs.colony.io/purser/interface-common-wallet-interface/) regarding the `setDefaultAddress()` method.

Common Wallet Interface Docs Spelling Fix

---

docs/_Interface_Common_Wallet_Interface.md
modules/node_modules/@colony/purser-core/defaults.js
modules/node_modules/@colony/purser-core/flowtypes.js
modules/node_modules/@colony/purser-core/helpers.js
modules/node_modules/@colony/purser-core/messages.js
modules/node_modules/@colony/purser-ledger/class.js
modules/node_modules/@colony/purser-ledger/staticMethods.js
modules/node_modules/@colony/purser-metamask/class.js
modules/node_modules/@colony/purser-metamask/defaults.js
modules/node_modules/@colony/purser-metamask/staticMethods.js
modules/node_modules/@colony/purser-software/class.js
modules/node_modules/@colony/purser-software/staticMethods.js
modules/node_modules/@colony/purser-trezor/class.js
modules/node_modules/@colony/purser-trezor/defaults.js
modules/node_modules/@colony/purser-trezor/index.js
modules/node_modules/@colony/purser-trezor/messages.js
modules/node_modules/@colony/purser-trezor/staticMethods.js
modules/tests/purser-core/helpers/transactionObjectValidator.test.js
modules/tests/purser-ledger/class.test.js
modules/tests/purser-ledger/staticMethods/signTransaction.test.js
modules/tests/purser-metamask/class.test.js
modules/tests/purser-software/class.test.js
modules/tests/purser-software/staticMethods/signTransaction.test.js
modules/tests/purser-trezor/class.test.js
modules/tests/purser-trezor/staticMethods/signTransaction.test.js

This PR removes and refactors the requirements for signing a transaction object.
Previously the `sign()` transaction method would require at least a `to`, `nonce` and `value` field props to be set. _(The remaining values were `default`ed)_
This was a problem for cases where you would want to deploy a contract, and in such cases you don't provide a destination address (`to`).
Here, we're removing all requirements _(just the implicit one remains -- all values must be passed in the form of an `Object`)_ from the `sign` methods of all wallet modules _(with the exception of Trezor, see note)_
_**Note: Trezor doesn't allow signing a transaction without a destination address being set (`to` field), and as such it makes it virtually impossible to deploy a contract using the Trezor wallet**_ …

Refactor transaction signing restrictions

---

jest.config.js
modules/node_modules/@colony/purser-core/flowtypes.js
modules/node_modules/@colony/purser-core/genericWallet.js
modules/node_modules/@colony/purser-software/class.js
modules/node_modules/@colony/purser-software/index.js
modules/node_modules/@colony/purser-software/staticMethods.js
modules/tests/mocks/ethers/utils/hdnode.js
modules/tests/mocks/ethers/utils/index.js
modules/tests/mocks/ethers/utils/json-wallet.js
modules/tests/mocks/ethers/utils/secret-storage.js
modules/tests/mocks/ethers/wallet/index.js
modules/tests/purser-core/genericWallet.test.js
modules/tests/purser-software/class.test.js
modules/tests/purser-software/open.test.js
modules/tests/purser-software/staticMethods/verifyMessage.test.js
yarn.lock

The recent `ethers` update to version `4` and the subsequent minor and patch versions changed a the import structure quite a bit, to the extent that `purser-software` failed to do it's most basic functions.
This PR changes most of the `import` structure and some of the method calls, to align with the new version.
Fixes:
Unit tests:

Fix ethers imports that changed in v4

---

modules/node_modules/@colony/purser-ledger/README.md
modules/node_modules/@colony/purser-metamask/README.md
modules/node_modules/@colony/purser-software/README.md
modules/node_modules/@colony/purser-software/index.js
modules/node_modules/@colony/purser-trezor/README.md

This PR is a hotfix to align the `create()` static method of `purser-software` to the new `mnemonic` naming scheme.
The `mnemonic` internal prop was renamed in [release v1.1.1](https://github.com/JoinColony/purser/releases/tag/v1.1.1) due to naming conflicts with the prop with the same name coming from `ethers`, but which was enforced in the new version as a getter only, so it became that we could not modify it anymore.
Also, this PR fixes the link to the _Common Wallet Interface_ documentation for all modules.

Fix `purser-software` mnemonic when creating a new instance

---

package.json
yarn.lock

This PR just merges the `@babel` suite of updates that Greenkeeper failed to automatically merge.
To be fair this was not it's fault, it was actually Circle, since it couldn't fetch the required packages from the `yarn` registry, so it failed the build. 
Greekeeper took this as a cue that something's wrong :)
Resolves #159

Update `monorepo.babel7` to the latest `7.1.4` version

---

.flowconfig
docs/_Modules_purser-metamask.md
jest.config.js
modules/node_modules/@colony/purser-core/genericWallet.js
modules/node_modules/@colony/purser-metamask/flowtypes.js
modules/node_modules/@colony/purser-metamask/helpers.js
modules/node_modules/@colony/purser-metamask/index.js
modules/node_modules/@colony/purser-metamask/messages.js
modules/node_modules/@colony/purser-metamask/methodLinks.js
modules/tests/mocks/@colony/purser-metamask/helpers.js
modules/tests/mocks/web3.js
modules/tests/purser-metamask/class.test.js
modules/tests/purser-metamask/helpers/detect.test.js
modules/tests/purser-metamask/helpers/getInpageProvider.test.js
modules/tests/purser-metamask/helpers/methodCaller.test.js
modules/tests/purser-metamask/open.test.js
modules/tests/purser-metamask/staticMethods/signMessage.test.js
modules/tests/purser-metamask/staticMethods/verifyMessage.test.js
package.json
yarn.lock

Metamask's new way of accessing the wallet accounts will go into effect on Nov 2nd: https://medium.com/metamask/https-medium-com-metamask-breaking-change-injecting-web3-7722797916a8
This change comes in as a result of implementing [EIP-1102](https://eips.ethereum.org/EIPS/eip-1102).
It now has a privacy mode which restricts accessing the contained accounts without first asking the user for access, by calling `window.ethereum.enable()`.
It also, will no longer inject the `Web3` instance in-page by default, so we'll have to do that ourselves.
The change that goes live on November the 2nd isn't going really to be breaking, as the privacy mode, although will be added in, it will be set to _off_ by default for a while.
Only after a certain amount of time has passed, that the switch will be …

Update `purser-metamask` to be EIP-1102 compliant

---

modules/node_modules/@colony/purser-metamask/helpers.js

This PR adds a simple check to `purser-metamask`'s `detect()` helper method to check if we're on the pre-release version of the EIP-1102 Metamask update.
We can tell this by checking the availability of the `window.ethereum.isUnlocked()` and `window.ethereum.isEnabled()` status checking methods.
If they're not available it means we're still in the days leading up to the [Nov. 2nd release.](https://medium.com/metamask/https-medium-com-metamask-breaking-change-injecting-web3-7722797916a8)

Fix `purser-metamask` to check if Metamask is on a pre-release version

---

modules/node_modules/@colony/purser-metamask/flowtypes.js
modules/node_modules/@colony/purser-metamask/methodLinks.js
modules/node_modules/@colony/purser-metamask/staticMethods.js
modules/tests/purser-metamask/staticMethods/signTransaction.test.js

Previously the transaction hash was being returned, which is different to how other wallet types behave. This caused code which expected the signed transaction hex string to be returned to break when used with the `purser-metamask` wallet.

Fix purser-metamask .sign() to return signed transaction hex

---

modules/node_modules/@colony/purser-core/validators.js
modules/tests/purser-core/validators/hexSequence.test.js

This was used to check data values were less than 1024 bytes, however lengths
greater than this are also valid. Therefore the check has been removed.
Tested with all wallets apart from Ledger, and appears to be working without problem. Particular care was taken to make sure this is working with Trezor wallets, as we believed this was why the check existed in the first place.

Remove length check from hexSequenceValidator

---

docs/_Interface_Common_Wallet_Interface.md
docs/_Modules_purser-software.md

This PR fixes the various links scattered through the docs, which turned out to 404.
Fixes:

Fix documentation external and internal linking

---

scripts/publish-to-npm.sh

This PR adds a couple of improvements to the release scripts so that we won't have to change it by hand every time we do a release. _(latest releases were all done this way...)_
Changes:
While it's not really feasible _(from a UX point of view)_ to a global OTP code to the release, we've done the next best thing, and add a login step + getting prompted before each package push, and as such, this also resolves #127

Improve NPM release script

---

package.json
yarn.lock

This is a manually opened PR fir a issue `greenkeeper` opened when updating `ethers`.
Since something broke the build, manual intervention is needed.
Changed:
Resolves #180

Manually update ethers to the latest version

---

docs/_Interface_Common_Wallet_Interface.md
modules/node_modules/@colony/purser-core/defaults.js
modules/node_modules/@colony/purser-core/helpers.js
modules/node_modules/@colony/purser-core/validators.js
modules/node_modules/@colony/purser-ledger/class.js
modules/node_modules/@colony/purser-ledger/staticMethods.js
modules/node_modules/@colony/purser-metamask/class.js
modules/node_modules/@colony/purser-metamask/staticMethods.js
modules/node_modules/@colony/purser-software/class.js
modules/node_modules/@colony/purser-software/staticMethods.js
modules/node_modules/@colony/purser-trezor/class.js
modules/node_modules/@colony/purser-trezor/staticMethods.js
modules/tests/mocks/@colony/purser-core/helpers.js
modules/tests/purser-ledger/class.test.js
modules/tests/purser-ledger/staticMethods/signMessage.test.js
modules/tests/purser-metamask/class.test.js
modules/tests/purser-metamask/staticMethods/signMessage.test.js
modules/tests/purser-software/class.test.js
modules/tests/purser-software/staticMethods/signMessage.test.js
modules/tests/purser-trezor/class.test.js
modules/tests/purser-trezor/staticMethods/signMessage.test.js

When calling `signMessage`, it is now possible to pass either `message` or
`messageData`. The latter can be a valid hex string or Uint8Array, and will be
passed to the underlying wallet without any additional encoding.
This solves scenarios where you wish to sign arbitrary data which cannot be represented as a UTF-8 string.
Closes #192

Add support for `messageData` options for `signMessage`

---

docs/_Docs_Development.md

Bug fix. This PR fixes an empty link to `Flow` in the docs.
I also searched for other empty links in the project and found no other occurrences.

Link to `Flow` homepage from docs

---

modules/node_modules/@colony/purser-metamask/package.json
package.json

This PR bumps the `monorepo` and `purser-metamask` to they're new version, in preparation for the upcoming hotfix release.

Release 2.1.1 Hotfix

---

docs/_Modules_purser-metamask.md
modules/node_modules/@colony/purser-metamask/index.js
modules/node_modules/@colony/purser-metamask/messages.js
modules/tests/purser-metamask/accountChangeHook.test.js

This PR works on exposing the `purser-metamask` `setStateEventObserver` helper method from within the package to ease users to hook into Metamask's UI account changes.
This needs to be wrapped inside some safeguards in order to prevent crashing the Wallet Instance Object.
Added:
Resolves #191

Expose `purser-metamask` account change hook method

---

package.json
yarn.lock

This PR updates the `eslint-plugin-flowtype` dev dependency to the latest version of `3.4.2`
This was done manually because circle crashed during the [`1270`](https://circleci.com/gh/JoinColony/purser/1270#tests/containers/1) build, which in turn screwed with greenkeeper's update flow.
Resolves #188

Update `eslint-plugin-flowtype` to the latest

---

package.json
yarn.lock

This PR updates the `camelcase` dev dependency to the latest version of `5.2.0`
This was done manually because circle crashed installing modules during the [`1400`](https://circleci.com/gh/JoinColony/purser/1400?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link) build, which in turn screwed with greenkeeper's update flow.
Resolves #208

Update `camelcase` to the latest

---

docs/_Modules_purser-metamask.md

This PR adds in a usage docs entry to `purser-metamask`'s `accountChangeHook` method, which exemplifies filtering inside the callback.
This is a preferred way of using this hook, as it will trigger even when opening the main Metamask UI, which is not something you want to update state on.

purser-metamask `accountChangeHook` docs example with filtering

---

modules/node_modules/@colony/purser-metamask/package.json
package.json

This PR bumps the `monorepo` and `purser-metamask` to their respective new versions, in preparation for the upcoming [`MINOR`](https://semver.org/) release.

Release v2.2.0 Minor

---

package.json
yarn.lock

This PR manually updates the `chokidar` dev dependency package to version `2.1.5` due to some initial build failing on CI when `greenkeeper` attempted to do this automatically.
Resolves #215

Upgrade `chokidar` dev dependency

---

package.json
yarn.lock

This PR manually updates the `@ledgerhq/hw-transport-u2f` dependency package to version `4.50.0` due to some initial build failing on CI when `greenkeeper` attempted to do this automatically.
Resolves #216

Upgrade `@ledgerhq/hw-transport-u2f` dependency

---

.eslintrc
package.json
yarn.lock

This PR manually pins the `eslint-plugin-import` dev dependency package to version `2.14.0` since that is the last know working version, with our specific monorepo configuration.
This is due to how, in version post `2.14.0`, the `eslint` plugin will not anymore do folder traversal, and will not detect our own packages under `modules/node_modules/@colony/...`.
Because of the above it will always complain that the packages are not installed
Resolves #218

Pin `eslint-plugin-import` to known working version

---

package.json
yarn.lock

This PR upgrades the `eslint-plugin-flowtype` dev dependency to version `3.11.1`.
This was done manually because GK couldn't automatically update due to a broken build.

Upgrade `eslint-plugin-flowtype` to version `3.11.1`

---

package.json
yarn.lock

This PR upgrades the `ethers` dev dependency to version `4.0.33`.
This was done manually because GK couldn't automatically update due to a broken build.
Resolves #240

Upgrade `ethers` to version `4.0.33`

---

package.json
yarn.lock

This PR upgrades the `eslint-config-airbnb-base` dev dependency to version `13.2.0`.
This was done manually because GK couldn't automatically update due to a broken build.
Resolves #244

Upgrade `eslint-config-airbnb-base` to version `13.2.0`

---

modules/node_modules/@colony/purser-metamask/staticMethods.js
modules/tests/purser-metamask/staticMethods/signMessage.test.js
modules/tests/purser-metamask/staticMethods/signTransaction.test.js

Due to the need to properly detect when a user has cancelled signing a transaction, throwing an error is better then just logging a warning.
As such, we've changed `purser-metamask` to throw on each instance where a user cancels, either signing a message, or a transaction.
*Changes*

purser-metamask will throw when cancelling signing a message or transaction

---

modules/node_modules/@colony/purser-core/package.json
modules/node_modules/@colony/purser-ledger/package.json
modules/node_modules/@colony/purser-metamask/package.json
modules/node_modules/@colony/purser-software/package.json
modules/node_modules/@colony/purser-trezor/package.json
package.json

This PR bumps the `monorepo` and all the modules to their respective new versions for the upcoming [`MINOR`](https://semver.org/) release:
- Monorepo: `2.3.0`
- `purser-core`: `2.2.1`
- `purser-ledger`: `1.3.0`
- `purser-metamask`: `2.3.0`
- `purser-software`: `1.2.5`
- `purser-trezor`: `1.2.3`

Release v2.3.0 Minor

---

modules/node_modules/@colony/purser-metamask/staticMethods.js
modules/node_modules/@colony/purser-trezor/staticMethods.js
modules/tests/purser-metamask/staticMethods/signMessage.test.js
modules/tests/purser-metamask/staticMethods/signTransaction.test.js
modules/tests/purser-metamask/staticMethods/verifyMessage.test.js
modules/tests/purser-trezor/staticMethods/signMessage.test.js
modules/tests/purser-trezor/staticMethods/signTransaction.test.js

This PR makes some changes to the error handling for the static methods of MetaMask/Trezor wallets, such that all errors can be caught, and error behaviour when cancelling signing is the same across wallet types.
*Trezor*
* Throw an error (rather than log a warning) when the user cancels signing a message/transaction with a Trezor wallet
* Make tests more specific for errors
*MetaMask*
* Ensure that the static methods (`signMessage`, `signTransaction`, `verifyMessage`) reject the promise when errors are encountered in their callbacks
* Define static method callbacks as separate methods
* Make tests more specific for errors
* Add missing JSDoc parameter for `signMessage`

Adjust error handling for static methods (MetaMask/Trezor)

---

modules/node_modules/@colony/purser-ledger/staticMethods.js
modules/node_modules/@colony/purser-metamask/staticMethods.js
modules/node_modules/@colony/purser-trezor/staticMethods.js
modules/tests/mocks/ethereumjs-tx.js
modules/tests/purser-ledger/staticMethods/signTransaction.test.js
modules/tests/purser-metamask/staticMethods/signTransaction.test.js
modules/tests/purser-trezor/staticMethods/signTransaction.test.js
scripts/build-individual-module.js

This PR makes a fix to the importing of `ethereumjs-tx`, which had a recent breaking change to its export.
**Changes**
* Fix the `ethereumjs-tx` import that was a breaking change of its `2.x` release
* Side fix: Remove a (seemingly harmless) typo in the build script

Fix `ethereumjs-tx` import

---

modules/node_modules/@colony/purser-ledger/package.json
modules/node_modules/@colony/purser-metamask/package.json
modules/node_modules/@colony/purser-trezor/package.json
package.json

This PR bumps the `monorepo` and all the modules to their respective new versions for the upcoming [`MINOR`](https://semver.org/) release:
- Monorepo: `2.4.1`
- `purser-ledger`: `1.3.1`
- `purser-metamask`: `2.3.2`
- `purser-trezor`: `1.3.1`

Release v2.4.1 Patch

---

modules/node_modules/@colony/purser-core/helpers.js
modules/node_modules/@colony/purser-core/normalizers.js
modules/node_modules/@colony/purser-core/utils.js
modules/node_modules/@colony/purser-ledger/flowtypes.js
modules/node_modules/@colony/purser-ledger/staticMethods.js
modules/node_modules/@colony/purser-metamask/helpers.js
modules/node_modules/@colony/purser-metamask/staticMethods.js
modules/node_modules/@colony/purser-software/class.js
modules/node_modules/@colony/purser-software/staticMethods.js
modules/node_modules/@colony/purser-trezor/class.js
modules/node_modules/@colony/purser-trezor/staticMethods.js
modules/tests/purser-ledger/staticMethods/signTransaction.test.js
modules/tests/purser-trezor/staticMethods/signTransaction.test.js

This PR makes some changes to transactions created with `ethereumjs-tx` such that the `chain` and `to` properties are supplied correctly; this fixes a bug where the recovery param wasn't validated correctly. 
**Changes**
* Adjust transaction params
* Adjust parameters for `ethereumjs-tx` transactions (recent breaking changes) and ensure that the chain ID is supplied; this fixes a bug where the recovery param wasn't validated correctly
* Fix logic for supplying a `to` property for transactions (it can also be `null`, not just `undefined`)
* Fix some Flow types
* Fix some comments
* Update/fix tests
* Minor normalizers refactor
* Fix Flow errors for string normalizers, require a string value
* Use a bound function for address/hex sequence normalizers

Adjust transaction parameters and prefixed string normalizers

---

modules/node_modules/@colony/purser-core/helpers.js
modules/node_modules/@colony/purser-ledger/staticMethods.js
modules/node_modules/@colony/purser-metamask/staticMethods.js
modules/node_modules/@colony/purser-trezor/staticMethods.js
modules/tests/mocks/@colony/purser-core/helpers.js
modules/tests/purser-ledger/staticMethods/signTransaction.test.js
modules/tests/purser-metamask/staticMethods/signTransaction.test.js
modules/tests/purser-trezor/staticMethods/signTransaction.test.js
package.json

This PR adds basic support for custom chains (i.e. anything but the default for `ethereumjs-tx`, which is `mainnet`). This is done by using the `ethereumjs-common` package to define a chain definition based on a default: either `mainnet` for chain IDs `1` (mainnet) and `1337` (local/private), or `5` for  `goerli`. Other chain IDs are sent as-is, which may cause validation errors if they are not supported by `ethereumjs-common`. 
Ideally, all chain definition should all be configurable when signing a transaction, but that would require a fairly significant API change.
**Additions**
* Add (limited) support for custom chains
* Add `ethereumjs-common` dependency (also a dependency of `ethereumjs-tx`)
* Define `getChainDefinition` helper in `purser-core`
**Changes**
* Implement custom chains …

Add (basic) custom chain support (e.g. Görli)

---

package.json
yarn.lock

This PR manually updates the `@ledgerhq/hw-app-eth` dependency package to version `4.68.1` manually, due to some initial build failing on CI when greenkeeper attempted to do this automatically.
Resolves #255

Upgrade `@ledgerhq/hw-app-eth` dependency

---

modules/node_modules/@colony/purser-core/package.json
modules/node_modules/@colony/purser-ledger/package.json
modules/node_modules/@colony/purser-metamask/package.json
modules/node_modules/@colony/purser-trezor/package.json
package.json

This PR bumps the `monorepo` and all the modules to their respective new versions for the upcoming [`MINOR`](https://semver.org/) release:
- Monorepo: `2.5.0`
- `purser-core`: `2.2.0`
- `purser-ledger`: `1.4.0`
- `purser-metamask`: `2.4.0`
- `purser-trezor`: `1.4.0`

Release v2.5.0 Minor

---

modules/node_modules/@colony/purser-core/defaults.js
modules/node_modules/@colony/purser-core/genericWallet.js
modules/node_modules/@colony/purser-core/helpers.js
modules/node_modules/@colony/purser-ledger/index.js
modules/node_modules/@colony/purser-metamask/staticMethods.js
modules/node_modules/@colony/purser-software/index.js
modules/node_modules/@colony/purser-trezor/index.js
modules/tests/purser-core/genericWallet.test.js
modules/tests/purser-ledger/open.test.js
modules/tests/purser-trezor/open.test.js
package.json
yarn.lock

This PR adds a workaround for an Infura issue (that becomes a problem with our MetaMask implementation) as documented [here](https://github.com/MetaMask/metamask-extension/issues/6704) and more specifically [here](https://github.com/ethers-io/ethers.js/issues/544#issuecomment-509663055). 
The crux of our issue is that `purser-metamask`'s `signTransaction` method attempts to get the transaction that MetaMask sent in the callback of `sendTransaction`, when it is pending. With most providers, the `getTransaction` method will respond with the transaction when it is pending, but Infura recently started returning an empty response.
The workaround involves attempting to get the transaction immediately, and if that fails, using a `web3` 0.20.x-compatible package (`await-transaction-mined`) to …

Add MetaMask/Infura workaround for pending transactions

---

modules/node_modules/@colony/purser-core/package.json
modules/node_modules/@colony/purser-ledger/package.json
modules/node_modules/@colony/purser-metamask/package.json
modules/node_modules/@colony/purser-software/package.json
modules/node_modules/@colony/purser-trezor/package.json
package.json

This PR bumps the `monorepo` and all the modules to their respective new versions for the upcoming [`PATCH`](https://semver.org/) release:
- Monorepo: `2.5.1`
- `purser-core`: `2.2.1`
- `purser-ledger`: `1.4.1`
- `purser-metamask`: `2.4.1`
- `purser-software`: `1.2.7`
- `purser-trezor`: `1.4.1`

Release v2.5.1 Patch

---

modules/tests/purser-metamask/staticMethods/signTransaction.test.js

This is a simple PR that properly mocks the `web3` global object, inside the `purser-metamask` `signTransaction` unit test, to include all the methods required, even those that are being called internally.

Fix Metamask unit tests improperly mocked web3 global object

---

.vscode/settings.json
modules/node_modules/@colony/purser-metamask/helpers.js
modules/node_modules/@colony/purser-metamask/index.js
modules/tests/purser-metamask/helpers/setStateEventObserver.test.js
package.json
scripts/build-individual-module.js
yarn.lock

Fix for https://github.com/JoinColony/purser/issues/288 to support the new ethereum provider api
- pursuer-metamask was failing on mobile
- Mobile version of metamask was using an etherum provider with a new unsupported api
- Re-implemented code to get the address and listen for account changes to respect new api whilst still being backwards compatible.
- Added tests
- Adjusted npm scripts to be windows compatible
- The test environment for mobile can be found here https://github.com/BrighTide/purser/tree/69b9cfb685cc8c0dc3ad217ffb9c80653d61277f/metmask-mobile-test

Support MetaMask mobile

---

README.md
package.json
packages/@purser/__mocks__/ethers/utils/index.ts
packages/@purser/signer-ethers/__tests__/EthersSigner.test.ts
packages/@purser/signer-ethers/package-lock.json
packages/@purser/signer-ethers/package.json
packages/@purser/signer-ethers/src/EthersSigner.ts

This PR fixes the `await on null` issues we were seeing using Infura's provider.
This was done by intercepting the response and in case it's `null`, just return `undefined` since `poll()` will retry on an undefined response.

Fix `await on null` error

---

package.json
packages/@purser/metamask/__tests__/helpers/detect.test.ts
packages/@purser/metamask/__tests__/open.test.ts
packages/@purser/metamask/package.json
packages/@purser/metamask/src/helpers.ts
packages/@purser/metamask/src/index.ts
packages/@purser/metamask/src/messages.ts
packages/@purser/metamask/src/types.ts
packages/@purser/signer-ethers/package.json

This PR changes the `metamask` package of this lib to support the recently deprecated Metamask API and updates according to the migration guide put out by metamask: https://docs.metamask.io/guide/provider-migration.html

Migrate metamask package to support Metamask v9

---

packages/@purser/metamask/package-lock.json
packages/@purser/metamask/package.json
packages/@purser/metamask/src/helpers.ts
packages/@purser/metamask/src/index.ts
packages/@purser/metamask/src/types.ts
packages/@purser/signer-ethers/package-lock.json
packages/@purser/signer-ethers/package.json
packages/@purser/signer-ethers/src/EthersSigner.ts

This PR improves Metamask's locked state detection by manually checking for the experimental `isUnlocked` value, as well as trying to access the accounts, in a sort of double blind test.
This change was made to overcome the `isUnlocked` to refresh it's returned value instantly. It needs a page refresh until it shows the new (unlocked) state.

Better Metamask Locked State Detection
